---
# tasks file for psmp installation

- name: Installation Block
  block:
    - name: Install PSMP rpm file
      shell: "rpm -i {{ psmp_installation_file }}"
      args:
        chdir: "{{ psmp_extract_folder }}/{{ psmp_component_folder }}"
    # yum:
      # name: "CARKpsmp-11.2.0-22.x86_64.rpm"
        # installroot: "{{ psmp_extract_folder }}/{{ psmp_component_folder }}"
        # state: present


- name: Set psmp exists
  set_fact:
    psmp_exists: true
  when: psmp_service_info.stat.exists
